name = "phd-tracker"
main = "src/index.js"
compatibility_date = "2024-04-05"

# 补充域名配置，解决部署警告
[[routes]]
pattern = "track.alyy.de"
custom_domain = true

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "DB"
id = "0fbd2a14cb894ee28db48469a08d17ec"
preview_id = "0fbd2a14cb894ee28db48469a08d17ec"
